name: build

on:
  workflow_call:

jobs:
  bicep-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build main.bicep
        run: |
          az bicep build --file ./infra/main.bicep

      - name: Build frontend.bicep
        run: |
          az bicep build --file ./infra/frontend.bicep

      - name: Build backend.bicep
        run: |
          az bicep build --file ./infra/backend.bicep