name: Build Bicep Files in Parallel

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bicepFile:
          - ./infra/backend.bicep
          - ./infra/frontend.bicep
          - ./infra/main.bicep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Bicep file
        run: az bicep build --file ${{ matrix.bicepFile }}