name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define multiple Bicep files to build in parallel
        bicepFile:
          - ./infra/backend.bicep
          - ./infra/frontend.bicep
          - ./infra/main.bicep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Bicep file
        # Use Azure CLI to build the specified Bicep file from the matrix
        run: az bicep build --file ${{ matrix.bicepFile }}