name: build

on:
  workflow_call:

jobs:
  bicep-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Bicep
        run: |
          az bicep build --file ./infra/main.bicep