name: Azure CI/CD Pipeline

# Triggers on a push to the main branch
# or when manually dispatched with an input 'stage'
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
         # Description of manual input
        description: 'Which stage to deploy to'
         # Make the input required
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test
      run: |

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Test
      run: |

    if: github.event_name == 'push'

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy_to_test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |

    if: github.event.inputs.stage == 'production'
