name: deploy-azure-view-environments

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:

  bicep-build:
    uses: ./.github/workflows/build.yml

  deploy-test:
    uses: ./.github/workflows/deploy.yml
    needs: bicep-build
    with:
      environmentType: Test
      resourceGroupName: rg-azure-view-test-001
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      AZURE_SWA_API_TOKEN: ${{ secrets.AZURE_SWA_API_TOKEN }}

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: rg-azure-view-prod-001
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      AZURE_SWA_API_TOKEN: ${{ secrets.AZURE_SWA_API_TOKEN }}